# Example values only
PAYPAL_CLIENT_ID = 'AbagERFAEHk8vv-'
PAYPAL_CLIENT_SECRET = 'EC8sWETAEWT_0'
DATABASE_URL = None

SES_SMTP_SERVER = 'email-smtp.us-east-1.amazonaws.com'
SES_USERNAME = 'AWETGAERAWER6P' # fake value
SES_PASSWORD = 'WERYHEWRYRTYHRYHRE' # fake value

SECRET_KEY ='6125fa95335849'