PAYPAL_CLIENT_ID = 'Abtv6CBUdwHk8vv-'
PAYPAL_CLIENT_SECRET = 'EC8skOMF-1O_0'
DATABASE_URL = None

SES_SMTP_SERVER = 'email-smtp.us-east-1.amazonaws.com'
SES_USERNAME = 'AKK56P'
SES_PASSWORD = 'BCWkwIaJIV'

SECRET_KEY ='6125fa95335849'